### ISSUE TITLE
Install Issue with python setup.py install

### ISSUE THREAD

**Issue by mikekoss** [Keck-DataReductionPipelines/KAI#9]
(iraf27) Mikemacbook2012-4:KAI mkoss$ python setup.py install
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    'write_to_template': VERSION_TEMPLATE})
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/dist.py", line 702, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/config.py", line 116, in parse_configuration
    options.parse()
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/config.py", line 426, in parse
    section_parser_method(section_options)
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/config.py", line 399, in parse_section
    self[name] = value
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/config.py", line 184, in __setitem__
    value = parser(value)
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 581, in __init__
    parsed.add(LegacySpecifier(specifier))
  File "/Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 84, in __init__
    raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
setuptools._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '2.7'

**Comment by mikekoss** [comment]
python --version
Python 2.7.18 :: Anaconda, Inc.
pip 19.3.1 from /Users/mkoss/anaconda3/envs/iraf27/lib/python2.7/site-packages/pip (python 2.7)

**Comment by percygomez** [comment]
Dear Issues,
I have the exactly same issue as described before. Thanks.

**Comment by amn3142** [comment]
Hi I have this issue too. Showing the same python version as well.

**Comment by amn3142** [comment]
This is leading to a later issue because no login.cl is being generated, so iraf variables aren't being defined.

**Comment by amn3142** [comment]
Uncommenting the line for system requirement fixed the installation problem.

**Comment by mikekoss** [comment]
> Uncommenting the line for system requirement fixed the installation problem.

@amn3142 Can you be more specific.  Which line of code where?

**Comment by amn3142** [comment]
> > Uncommenting the line for system requirement fixed the installation problem.
> 
> @amn3142 Can you be more specific. Which line of code where?

I must have been sleep deprived when I wrote that, it was total nonsense sorry!! Edited the comment to what it should have said...

**Comment by mikekoss** [comment]
@amn3142 thanks so much for posting that.  This solved my install issue and was able to reduce the data...

**Comment by jluastro** [comment]
Fixed in version v1.0.1. Let me know if this helps!
